# Quantum teleportation 

La teleportación cuántica es una técnica para moverse por los estados cuánticos aunque no exista un canal de enlace entre el estado cuántico y su receptor. 

Por ejemplo, Alice quiere enviar información cuántica para Bob. Supongamos que se trata del 
estado qubit 

$$
| \phi \rangle
= 
\alpha
| 0 \rangle
+
\beta
|1\rangle.
$$
Transmitirle la información consistiría en enviarle información a Bob sobre $\alpha$ y $\beta$. 

Sin embargo el **Teorema de no clonación** 
establece que 

*No existe operador unitario U actuando sobre $\mathcal{H}_A \otimes \mathcal{H}_B$ de 
forma que para todos los estados normalizados 
$| \phi \rangle_A$ y 
$| e \rangle_B$ en 
$\mathcal H$ cumplan que*


$$
U 
| \phi \rangle_A
| e \rangle_B
= 
| \phi \rangle_A
| \phi \rangle_B
$$

Es decir, no podemos hacer una copia exacta de un estado cuántico desconocido, solo podremos copiar los estados clásicos (no las superposiciones). 

## Un poco de contexto   

El primero de los artículos científicos al respecto fue
*Teleporting an Unknown Quantum State via Dual Classical and Einstein-Podolsky-Rosen Channels* 
publicado por  C. H. Bennett, G. Brassard, C. Crépeau, R. Jozsa, A. Peres, and W. K. Wootters en 1993. 

Se realizó experimentalmente en 1997 por dos grupos de investigadores Sandu Popescu y Anton Zeilinger respectivamente.  

## Protocolo de Teleportación Cuántica 

### Requisitos previos 
Para transferir un qubit, Alice y Bob usaran un tercer canal (Telamon en la notación de IBM) para enviar un par de qubit entrelazados. 

Además, para la correcta comprensión del algoritmo, se requerirá el uso de los estados de Bell. 
En primer lugar, una puerta de Hadamard nos permite pasar del estado $|00\rangle$ a $\frac{(|0\rangle+|1\rangle)|0\rangle}{\sqrt{2}}$. Y si aplicamos a continuación un CNOT, obtendremos el estado $\frac{(|00\rangle+|11\rangle)}{\sqrt{2}}$. Esta transformación de estados resultante, es la que denominaremos como estado de Bell, y lo denotaremos como $|\beta_{00}\rangle$. De este modo, los estados posibles son:
$$
|\beta_{00}\rangle := \frac{(|00\rangle+|11\rangle)}{\sqrt{2}}
$$
$$
|\beta_{01}\rangle := \frac{(|01\rangle+|10\rangle)}{\sqrt{2}}
$$
$$
|\beta_{10}\rangle := \frac{(|00\rangle-|11\rangle)}{\sqrt{2}}
$$
$$
|\beta_{11}\rangle := \frac{(|01\rangle-|10\rangle)}{\sqrt{2}}
$$

Desde un punto de vista general los estados de Bell los podemos resumir en la siguiente definición:

$$
|\beta_{xy}\rangle = \frac{|0,y\rangle + (-1)^x|1,\overline{y}\rangle}{\sqrt{2}}
$$

donde $\overline{y}$ es la negación de $y$.

### Paso generales 

1. Un estado de Bell es generado cuando se envía un qubit de A a B.   

2. Una medida de Bell del estado cuántico y de el qubit que se va a teletransportar ($| \phi \rangle$) es realizado en A y esto permite que uno de los cuatro estados que se van a medir puedan ser codificados en dos bits clásicos de información.   

3. Usando el canal tradicional los dos bits se mandan de A a B. 

4. Como resultado de la medida realizada en A, el estado de Bell está en B.  Uno de esos cuatro estados es idéntico al estado de $| \phi \rangle$ y los otros tres se le parecen. 

## Formulación formal   

Sea $| \psi \rangle$ el qubit de Alice que quiere enviar a Bob. 

El qubit puede escribirse como 

$$
| \psi \rangle_C 
= 
\alpha
| 0 \rangle_C
+
\beta 1 \rangle_C.
$$
Donde el subíndice C se usa para distinguir este estado de A a B. 

### Paso previos de Alice 

#### Puerta CNOT 

Alice aplicará una puerta CNOT a sus dos qubits. De esta manera uno de los qubit nos servirá como control mientras que el otro como objetivo. 

Recordemos que aplicar una puerta CNOT se puede ver como aplicar un operador de estados, matriz 

$$
CNOT
= 
\begin{bmatrix}
1 &  0 &  0 &  0 \\
0&   1 &  0 &  0   \\
0 &  0 &  0 &  1   \\
0 &  0&   1&   0  \\
\end{bmatrix} 
$$
De esta manera 

$$
| \psi_1 \rangle 
= 
CNOT 
| \psi_0 \rangle
= 
\frac{1}{2}
(
    \alpha 
    | 0 \rangle
    ( 
        | 0 0 \rangle
        +
        | 11 \rangle
    )
    +
    \beta 
    | 1 \rangle
    ( 
        | 1 0 \rangle
        +
        | 0 1 \rangle
    )
).
$$

### Operador de Hadamard 

A continuación Alice aplicará el operador de Hadamard 

$$
H = 
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1 &1 \\
1 &-1  \\
\end{bmatrix} 
$$

### Transmisión 
El protocolo requiere ahora que Alice y Bob compartan un estado máximo entrelazado. Este será uno de estos cuatro (no importa cual)

$$
\begin{align}
&
| \phi ^+ \rangle_{A B}
= 
\frac{1}{\sqrt{2}}
(
    |0 \rangle_A \otimes |0 \rangle_B
    +
    |1 \rangle_A \otimes |1 \rangle_B
),
\\
&
| \psi ^+ \rangle_{A B}
= 
\frac{1}{\sqrt{2}}
(
    |0 \rangle_A \otimes |1 \rangle_B
    +
    |1 \rangle_A \otimes |0 \rangle_B
),
\\
&
| \psi ^-\rangle_{A B}
= 
\frac{1}{\sqrt{2}}
(
    |0 \rangle_A \otimes |1 \rangle_B
    -
    |1 \rangle_A \otimes |0 \rangle_B
),
\\ 
&
| \phi ^- \rangle_{A B}
= 
\frac{1}{\sqrt{2}}
(
    |0 \rangle_A \otimes |0 \rangle_B
    -
    |1 \rangle_A \otimes |1 \rangle_B
).
\end{align}
$$

Sin pérdida de generalidad supondremos que el estado compartido ha sido 
$| \phi ^+ \rangle_{A B}$, donde
el subíndice A y B en el estado entrelazado indica si ese estado pertenece a la partícula de Alice o a la de Bob. Recordemos que C era el estado que Alice pretendía teletransportar. 


Alice toma una de las partículas del par, entonces tiene dos, la C que es la que quiere teletransportar y ya las ha entrelazado en los dos pasos previos A. Bob tiene una. 

El estado total es el siguiente: 

$$
| \psi \rangle_C
\otimes 
| \phi^+ \rangle_{AB}
= 
(
    \alpha
    | 0 \rangle_C
    +
    \beta
    | 1 \rangle_C
)
\otimes
\frac{1}{\sqrt{2}}
(
    |0 \rangle_A \otimes |0 \rangle_B
    +
    |1 \rangle_A \otimes |1 \rangle_B
).
$$
Alice hace una medición local en los cuatro estados en las dos partículas en su posesión, que procedemos a escribir para que quede claro: 

$$
\begin{align}
% primera ecuación 
&
| 0 \rangle
\otimes
| 0 \rangle
= 
\frac{1}{\sqrt{2}}
(
| \phi^+ \rangle
+ 
| \phi^- \rangle
)
\\
% Segunda ecuación 
&
| 0 \rangle
\otimes
| 1 \rangle
= 
\frac{1}{\sqrt{2}}
(
| \psi^+ \rangle
+ 
| \psi^- \rangle
)
\\
% Tercera ecuación
&
| 1 \rangle
\otimes
| 0 \rangle
= 
\frac{1}{\sqrt{2}}
(
| \psi^+ \rangle
- 
| \psi^- \rangle
)
\\
% Cuarta ecuación
&
| 1 \rangle
\otimes
| 1 \rangle
= 
\frac{1}{\sqrt{2}}
(
| \phi^+ \rangle
-
| \phi^- \rangle
)
\\
\end{align}
$$

Después de expandir la expresión para 
$$
| \psi \rangle_C
\otimes 
| \phi^+ \rangle_{AB},
$$
se aplican las identidades a los qubits con subíndices  A y C.  
En nuestro caso particular esto sería: 

$$
\alpha
\frac{1}{\sqrt{2}}
| 0 \rangle_C
\otimes
| 0 \rangle_A
\otimes
| 0 \rangle_B
=
\alpha 
\frac{1}{2}
(
    | \phi^+ \rangle_{CA}
    + 
    | \phi^- \rangle_{CA}
).
$$
(Para los otros términos se haría de manera similar). 

Combinando estos términos, los tres estados de partícula de A, B y C juntos obtenemos la siguiente ecuación del estado de superposición: 

$$
\begin{align}
| \psi \rangle_C
\otimes
| \phi^+ \rangle_{AB}
=  
\frac{1}{2}
( 
&
|  \phi^+ \rangle_{CA}
\otimes
( 
    \alpha | 0 \rangle_B 
    +
    \beta | 1 \rangle_B
)
\\
+ &
| \phi^- \rangle_{CA}
\otimes
( 
    \alpha | 0 \rangle_B 
    -
    \beta | 1 \rangle_B
)
\\
+ &
| \psi^+ \rangle_{CA}
\otimes
( 
    \alpha | 1 \rangle_B 
    +
    \beta | 0 \rangle_B
)
\\
+ &
| \psi^- \rangle_{CA}
\otimes
( 
    \alpha | 1 \rangle_B 
    -
    \beta | 0 \rangle_B
)
\\
).
\end{align}
$$

Notemos qe las partículas siguen igual ya que no hemos 
aplicado ninguna transformación a las operaciones. 

La teletrasportación ocurre cuando Alice mide uno de sus qubits A y C en la base de Bell.


$$
| \phi^+ \rangle_{CA}, 
| \phi^- \rangle_{CA}, 
| \psi^+ \rangle_{CA}, 
| \psi^- \rangle_{CA}.
$$


Equivalentemente la medida también puede darse en una base computacional con combinaciones

$$
\left\{
| 0 \rangle, 
| 1 \rangle
\right\}
$$
mapeando cada estado de Bell de manera única con un elemento de 

$$
\left\{
| 0 \rangle
\otimes
| 0 \rangle,
| 0 \rangle
\otimes
| 1 \rangle,
| 1 \rangle
\otimes
| 0 \rangle,
| 1 \rangle
\otimes
| 1 \rangle
\right\}.
$$

De esta manera los estado de Alice colapsarán con igualdad de probabilidad en uno de los siguientes estados: 

$$
| \phi^+ \rangle_{CA}
\otimes
(
    \alpha | 0 \rangle_B
    +
    \beta | 1 \rangle_B
),
$$

$$
| \phi^- \rangle_{CA}
\otimes
(
    \alpha | 0 \rangle_B
    -
    \beta | 1 \rangle_B
),
$$

$$
| \psi^+ \rangle_{CA}
\otimes
(
    \alpha | 1 \rangle_B
    +
    \beta | 0 \rangle_B
),
$$

$$
| \psi^- \rangle_{CA}
\otimes
(
    \alpha | 1 \rangle_B
    -
    \beta | 0 \rangle_B
).
$$


El entrelazamiento de las partículas de Alice y Bob se ha roto. 

Bob toma ahora uno de los cuatro estados posibles
que se le parece al estado que va a ser teletrasportado. 

Como resultado de la medición de Alice, ella puede enviar el resultado de la medición a Bob por el canal de transmisión tradicional. 

De esta forma, habiendo recibido tal información, Bob realizará las siguiente operaciones a su partícula para transformarla en el estado deseado. 

- Si Alice indica que su resultado es $|\phi^+ \rangle_{CA}$
entonces Bob sabe que su cubit está en el estado deseado. 

- Si el mensaje indica que 
$|\phi^- \rangle_{CA}$
entonces deberá de transformarlo por la puerta cuántica. 

$$
\sigma_3 
= 
\begin{bmatrix}
1 & 0 \\
0 & -1 
\end{bmatrix}
$$
para recuperar el estado. 

-  Si el mensaje de Alice se corresponde a $| \psi^+ \rangle_{CA}$, Bob utilizará la puerta:

$$
\sigma_1 
= 
\begin{bmatrix}
0 & 1 \\
1 & 0 
\end{bmatrix}
$$
a su qubit. 

- Finalmente la puerta apropiada es 

$$
\sigma_3 \sigma_1
= 
- \sigma_1 \sigma_3 
= 
i \sigma_2
= 
\begin{bmatrix}
0 & 1 \\
-1 & 0 
\end{bmatrix}.
$$


Después de esta operación, el quibit de Bob estará en el estado 

$$
| \psi \rangle_B
= 
\alpha | 0 \rangle_B
+
\beta | 1 \rangle_B.
$$
Notemos que la teleportación no consiste en copiar los qubits y por tanto es consistente con el teorema de la no clonación. 

Esto se puede generalizar, por cada qubit teletransportado Alice necesita enviar a Bob dos bits de información clásicos. 

# Fuentes 
- Página 26 del libro Quantum Computation and Quantum Information
10th Anniversary Edition
Michael A. Nielsen & Isaac L. Chuang

- https://es.wikipedia.org/wiki/Teorema_de_no_clonación

-  https://qiskit.org/textbook/ch-algorithms/teleportation.html#3.1-How-Will-We-Test-the-Protocol-on-a-Quantum-Computer?-
- https://en.wikipedia.org/wiki/Quantum_teleportation
- Bennett, Charles H.; Brassard, Gilles; Crépeau, Claude; Jozsa, Richard; Peres, Asher; Wootters, William K. (29 March 1993). "Teleporting an unknown quantum state via dual classical and Einstein-Podolsky-Rosen channels". Physical Review Letters. 70 (13): 1895–1899. Bibcode:1993PhRvL..70.1895B.
- D. Boschi; S. Branca; F. De Martini; L. Hardy; S. Popescu (1998). "Experimental Realization of Teleporting an Unknown Pure Quantum State via Dual Classical and Einstein-Podolsky-Rosen Channels". Physical Review Letters. 80 (6): 1121–1125. arXiv:quant-ph/9710013. Bibcode:1998PhRvL..80.1121B.